#!/usr/bin/env python3
"""
Narrative Stage JSON to Translation Key Migrator
Converts hardcoded "text" fields to "text_key" and extracts text to PO file.

Usage:
    python3 migrate_narrative_to_translation_keys.py
"""

import json
import os
from pathlib import Path

# Configuration
NARRATIVE_STAGES_DIR = "data/narrative_stages"
OUTPUT_PO_FILE = "data/content_packs/genesis/translations/narrative_en.po"
DRY_RUN = False  # Set to True to preview changes without writing

# Track extracted strings
extracted_strings = {}

def create_translation_key(stage_id: str, state_name: str = "TEXT") -> str:
    """Create a translation key from stage ID and state name."""
    # Convert stage_id to uppercase and replace underscores
    key_base = stage_id.upper().replace("-", "_")
    return f"NARRATIVE_{key_base}_{state_name.upper()}"

def process_narrative_stage(file_path: Path) -> bool:
    """Process a single narrative stage JSON file."""
    print(f"\n📄 Processing: {file_path.name}")

    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            data = json.load(f)

        stage_id = data.get("id", file_path.stem)
        modified = False

        # Process states array
        if "states" in data and isinstance(data["states"], list):
            for idx, state in enumerate(data["states"]):
                # Check if state has "text" field (hardcoded)
                if "text" in state and "text_key" not in state:
                    text_content = state["text"]
                    state_name = state.get("name", f"state_{idx}")

                    # Create translation key
                    trans_key = create_translation_key(stage_id, state_name)

                    # Store the extracted string
                    extracted_strings[trans_key] = text_content

                    # Replace "text" with "text_key"
                    state["text_key"] = trans_key
                    del state["text"]

                    modified = True
                    print(f"  ✓ Migrated state '{state_name}': {trans_key}")

        # Write back if modified
        if modified and not DRY_RUN:
            with open(file_path, 'w', encoding='utf-8') as f:
                json.dump(data, f, indent=2, ensure_ascii=False)
            print(f"  💾 Updated: {file_path.name}")
            return True
        elif modified and DRY_RUN:
            print(f"  🔍 [DRY RUN] Would update: {file_path.name}")
            return True
        else:
            print(f"  ⏭️  No changes needed")
            return False

    except Exception as e:
        print(f"  ❌ ERROR: {e}")
        return False

def append_to_po_file(po_file_path: Path):
    """Append extracted strings to the PO file."""
    print(f"\n📝 Appending {len(extracted_strings)} strings to: {po_file_path}")

    if DRY_RUN:
        print("  🔍 [DRY RUN] Would append:")
        for key, value in extracted_strings.items():
            print(f"     {key}: {value[:50]}...")
        return

    # Read existing PO file
    existing_keys = set()
    if po_file_path.exists():
        with open(po_file_path, 'r', encoding='utf-8') as f:
            content = f.read()
            # Extract existing msgid entries
            for line in content.split('\n'):
                if line.startswith('msgid "') and not line.startswith('msgid ""'):
                    key = line.replace('msgid "', '').replace('"', '')
                    existing_keys.add(key)

    # Append new translations
    with open(po_file_path, 'a', encoding='utf-8') as f:
        f.write("\n# =============================================================================\n")
        f.write("# AUTO-MIGRATED NARRATIVE STAGE TEXTS\n")
        f.write(f"# Generated by migrate_narrative_to_translation_keys.py\n")
        f.write("# =============================================================================\n\n")

        for key, text in sorted(extracted_strings.items()):
            if key not in existing_keys:
                # Escape quotes and newlines for PO format
                escaped_text = text.replace('"', '\\"').replace('\n', '\\n')

                f.write(f'msgid "{key}"\n')
                f.write(f'msgstr "{escaped_text}"\n')
                f.write('\n')
                print(f"  ✓ Added: {key}")
            else:
                print(f"  ⏭️  Skipped (already exists): {key}")

    print(f"  💾 Updated: {po_file_path}")

def main():
    print("🌍 Narrative Stage Translation Key Migration")
    print("=" * 60)

    if DRY_RUN:
        print("⚠️  DRY RUN MODE - No files will be modified")

    # Get all narrative stage JSON files
    stages_dir = Path(NARRATIVE_STAGES_DIR)
    json_files = list(stages_dir.glob("*.json"))

    print(f"\n📁 Found {len(json_files)} narrative stage files")

    # Process each file
    modified_count = 0
    for json_file in sorted(json_files):
        if process_narrative_stage(json_file):
            modified_count += 1

    # Append extracted strings to PO file
    if extracted_strings:
        po_path = Path(OUTPUT_PO_FILE)
        po_path.parent.mkdir(parents=True, exist_ok=True)
        append_to_po_file(po_path)

    # Summary
    print("\n" + "=" * 60)
    print("📊 SUMMARY")
    print(f"   Files processed: {len(json_files)}")
    print(f"   Files modified: {modified_count}")
    print(f"   Strings extracted: {len(extracted_strings)}")

    if DRY_RUN:
        print("\n💡 This was a dry run. Set DRY_RUN=False to apply changes.")
    else:
        print("\n✅ Migration complete!")
        print(f"\n📝 Next steps:")
        print(f"   1. Review changes in narrative stage JSON files")
        print(f"   2. Review new translations in {OUTPUT_PO_FILE}")
        print(f"   3. Translate to other languages (Spanish, Portuguese, etc.)")
        print(f"   4. Test in Godot Editor (reimport PO files)")

if __name__ == "__main__":
    main()
